# Site settings
locale                   : "en-US"
title                    : "David Yi"
title_separator          : "-"
name                     : &name "David Yi"
description              : &description "Assistive robotics research at the Carnegie Mellon Robotics Institute."
url                      : "https://dhyi-svg.github.io"
baseurl                  : ""
repository               : "dhyi-svg/dhyi-svg.github.io"

# Site author (this is the sidebar)
author:
  avatar           : "profile.jpg"
  name             : *name
  pronouns         :
  bio              : "Statistics &amp; Machine Learning undergraduate at Carnegie Mellon"
  location         : "Pittsburgh, PA"
  employer         : "Carnegie Mellon University"
  uri              :
  email            : "dhyi@andrew.cmu.edu"
  github           : "dhyi-svg"
  linkedin         : "YOUR-LINKEDIN-USERNAME"
  googlescholar    :
  orcid            :
  twitter          :

# Reading files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Collections
collections:
  portfolio:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: America/New_York

# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
